lang: ruby

rvm: 2.6

branches:
  only:
    - master

script:
  - bundle exec rspec --exclude-pattern spec/**/*_integration_spec.rb
  - test -z $ACCESS_KEY_ID -a -z $ACCESS_KEY_SECRET || bundle exec rspec -P spec/**/*_integration_spec.rb