language: ruby

cache: bundler

rvm: 
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby-9.1

branches:
  only:
    - master

install:
  - gem update --system
  - gem install bundler
  - gem install rspec

before_install:
  - bundle install

script:
  - bundle exec rspec --exclude-pattern spec/**/*_integration_spec.rb
  - test -z $ACCESS_KEY_ID -a -z $ACCESS_KEY_SECRET || bundle exec rspec -P spec/**/*_integration_spec.rb